blueprint: ## Generate all blueprints file
	@if ! type orbit >/dev/null 2>&1; then echo "Missing orbit dependency, please install from https://github.com/gulien/orbit/"; exit 1; fi
	orbit run generate
	@sed -i '1i\# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.blueprint)' Dockerfile.*

test-latest: test-20 ## Test the latest build only

test-20: blueprint ## Test node 20 build only
	BRANCH=master VARIANT=20-bullseye TAG=v2-20-bullseye ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	BRANCH=master VARIANT=20-apache-bullseye TAG=v2-20-apache-bullseye ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	notify-send -u critical "Tests passed with success"

clean: ## Clean dangles image after build
