blueprint: ## Generate all blueprints file
	@if ! type orbit >/dev/null 2>&1; then echo "Missing orbit dependency, please install from https://github.com/gulien/orbit/"; exit 1; fi
	orbit run generate
	@sed -i '1i\# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.blueprint)' Dockerfile.*

test-latest: test-20 ## Test the latest build only

test-14: ## Test node 14 build only
test-16: ## Test node 16 build only
test-18: ## Test node 18 build only
test-20: ## Test node 20 build only
test-%: blueprint ## Test node X build
	BRANCH=master VARIANT=$(*)-bullseye TAG=v2-$(*)-bullseye ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	BRANCH=master VARIANT=$(*)-bullseye-build TAG=v2-$(*)-bullseye-build ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	BRANCH=master VARIANT=$(*)-apache-bullseye TAG=v2-$(*)-apache-bullseye ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	BRANCH=master VARIANT=$(*)-apache-bullseye-build TAG=v2-$(*)-apache-bullseye-build ./build-and-test.sh || (notify-send -u critical "Tests failed" && exit 1)
	notify-send -u critical "Tests passed with success for $*"

clean: ## Clean dangles image after build
